[workspace]
members = ["ents", "ents-sqlite", "ents-heed", "ents-test-suite"]
resolver = "2"

[workspace.package]
version = "0.1.3"
homepage = "https://github.com/blmarket/ents"
repository = "https://github.com/blmarket/ents"
edition = "2021"
authors = [ "blmarket@gmail.com" ]
